const quotes = [
  "Start strong, finish stronger 💪",
  "Push code, not deadlines 🔥",
  "Break bugs, not dreams ✨",
  "Eat. Sleep. Code. Repeat. 🔁",
  "Commit like your streak depends on it 🟩",
  "One bug at a time 🐛",
  "Just ship it 🚀",
  "Console.log('Success') ✅",
  "CSS is just vibes 🌀",
  "Keep calm and push to GitHub 👾",
  "Keyboard louder than my will to live 💻💀",
  "404: Motivation not found 😅",
  "You miss 100% of the bugs you don’t fix 🐞",
  "Stack Overflow is my spirit animal 🐱‍👓",
  "No WiFi, no life 🌐",
  "Brb debugging life 😩",
  "Your brain is compiling. Wait... ⏳",
  "Pixel perfect or nothing 🔍",
  "Git commit -am 'I have no idea what I'm doing' 🤡",
  "Friday deploy? I like danger 💣",
  "Push dreams, not drama 😌",
  "Fail, fix, flex 💅",
  "Coffee first, syntax later ☕",
  "You are the framework. Build yourself 💪",
  "Every line you write is a step to glory 👣",
  "Ctrl + Z but for life pls 😭",
  "Trust the process. And git push 🚀",
  "Make it work. Make it pretty. Make it fast ⚙️",
  "Daily grind > fake hustle 🧱",
  "Front-end? Back-end? I’m the whole damn stack 🧠",
  "Dev by day, debug by night 🌙",
  "Less stress, more commits 💚",
  "What would Linus do? 🧓",
  "Your repo reflects your soul 🕊️",
  "Green squares = real power 🟩",
  "Read docs, not drama 📚",
  "Don't wish for it. Code for it ✨",
  "Nobody starts great, everyone starts 😤",
  "Addicted to progress 🔥",
  "Hard reset? Nah, I refactor 🛠️",
  "Zero bugs? You're dreaming 😴",
  "My IDE knows me better than my friends 💔",
  "If it compiles, it ships 🚚",
  "Make errors your allies 💥",
  "Progress, not perfection 🧘",
  "Life’s a loop. Optimize it 🔄",
  "Push positivity with every commit 🙌",
  "Debug the day 🧠",
  "Write clean. Live clean ✨",
  "Don’t just learn. Build 💻",
  "Every bug fixed = 1 XP gained 🆙",
  "Version control your chaos 🌀",
  "You’re not stuck, you're buffering ⏳",
  "Creativity is just structured madness 🎨",
  "Test more, stress less ✅",
  "Dreams in dark mode 🌚",
  "Passion is your true framework 💫",
  "If it was easy, it wouldn’t be fun 🔥",
  "Open source your spirit 💖",
  "Fake it till you make an API 💅",
  "Sleep is temporary. Projects are forever 🧠💤",
  "Design the life you want 🧩",
  "Syntax before sleep 💤",
  "Fear the coder with coffee ☕👀",
  "Dark mode heals me 🌌",
  "Keyboard clack = healing sound 🔊",
  "Behind every click is chaos 😈",
  "Make side projects your superpower 💡",
  "You vs yesterday. You win? 🥇",
  "There’s no bug I can’t beat 👊",
  "More reps, more reps... of code 💪",
  "Live like you're open-sourced 🫂",
  "Find your 'why', then debug the 'how' ❓",
  "Don’t cry. Try-catch 🧠",
  "Believe in the brackets {} 🧙‍♂️",
  "Code is the art of logic 🎭",
  "Make your own library of greatness 📦",
  "Refactor your mindset 🔁",
  "Inhale confidence. Exhale bugs 🧘‍♂️",
  "Stay humble, commit often 🙏",
  "Logs don't lie 📝",
  "Always in beta, never broken 🔄",
  "Every PR is proof of progress 🫡",
  "The best projects start with ‘what if’ 🤔",
  "Bug fixing builds character 💀",
  "Ship fast, learn faster 📦",
  "Push peace into the terminal 🕊️",
  "You're building the future. Literally 🧱",
  "Code for impact. Not likes 💥",
  "You're not lazy, you're caching energy 💤",
  "Even God rested. Take breaks 🙏",
  "Don't compare commits. Compare growth 📈",
  "Creativity compiles 🌟",
  "IDE: I Do Everything 😤",
  "Be proud of the mess. It means progress 🚧",
  "Dreams are just apps waiting to be built 💤📱",
  "Never underestimate your hello world 🌍",
  "Keep shipping. Keep learning 📦📚",
  "Talk less, code more 😎",
  "You're a walking framework 🔥",
  "UI is personality. Backend is soul 💅",
  "Let your bugs build you 🛠️",
  "Not a coder. A sorcerer 🔮",
  "Night owl? More like night dev 🦉",
  "Failing is just compiling lessons 🧠",
  "Don't just debug code. Debug your doubt 💥",
  "React, but don’t overthink 🤯",
  "Deploy dreams, not just features 💭",
  "Your repo is your resume 🔥",
  "You survived another merge conflict. Respect 💯",
  "Ctrl + S your goals 💾",
  "Find the flow state and stay there 🌊",
  "Terminal is my therapist 🧠",
  "Your function has purpose() 🔄",
  "Add value, not just features 💰",
  "Don’t rage quit. Refactor 🙃",
  "Refactor until it feels like art 🎨",
  "Your grind is compiling success 🛠️",
  "Not procrastinating—just ideating 💡",
  "Push joy, not pressure 🧘‍♀️",
  "You’re the only package that matters 📦✨",
  "Keep pushing. Git never lies 🔥",
  "Commit to growth every day 📅",
  "Dark mode. Light soul ✨",
  "Passion is permanent. Bugs are temporary 🔧",
  "Every keystroke is a pixel of your legacy 💫",
  "Write code like no one’s watching 🕺",
  "Push the life you want to live 🚀",
  "Even semicolons can’t stop you ;)",
  "Hack your own path 🔓",
  "Sleepy coder still ships 💻💤",
  "Make your repo a reflection of your journey 🛣️",
  "Work smart. Git hard 💪",
  "Your code speaks louder than words 🔊",
  "Stay weird. Stay wild. Stay building 🔮",
  "Add fire to your functions 🔥",
  "Think. Build. Repeat 🔁",
  "May your code always compile 🙏",
  "Blessed with bugs to fix 🐞🙏",
  "One line at a time. One day at a time 📈",
  "Turn coffee into code ☕💻",
  "Your growth is the real stack 💯",
  "Push dreams to prod 🌟",
  "Success is a series of commits 🔗",
  "Don’t fear the error log 😈",
  "Git add . your courage ✅",
  "Go fullstack on life 🔥",
  "Write like an artist. Build like an engineer 🎨🛠️",
  "You are the patch note 🛠️",
  "Make your code legendary 🧙",
  "It’s not just code. It’s craft 🪡",
  "Run the script of your life 🎬",
  "Haters gonna hate. Coders gonna build 👊",
  "Don't stop now. You're compiling greatness 🏗️",
  "You're an idea machine 🧠💡",
  "Keyboard therapy all day 🛠️",
  "10x coder? Nah, 100x mindset 💯",
  "Imposter syndrome ain't real. Your code is 🔥",
  "Your streak = your story 🟩📖",
  "Pushing greatness daily 🔥"
];

function getRandomQuote() {
  const index = Math.floor(Math.random() * quotes.length);
  return quotes[index];
}

const quoteList = document.getElementById("quote-list");
quoteList.innerHTML = `<li>${getRandomQuote()}</li>`;
